server:
  port: 8090
  tomcat:
      max-http-form-post-size: -1
      uri-encoding: UTF-8
      max-threads: 1000
      min-spare-threads: 30
      max-swallow-size: -1
  connection-timeout: 5000ms
  servlet:
      context-path: /ct-website

#spring相关配置
spring:
  profiles:
      active: dev
  #静态资源路径
  resources:
    static-locations: classpath:/resources/,classpath:/static/,classpath:/template/
  #模板引擎配置
  thymeleaf:
#    prefix: "classpath:/templates/"
#    suffix: ".html"
    cache: false
  #redis
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

#SpringBoot整合MybatisPlus
mybatis-plus:
  #设置别名包
  type-aliases-package: com.codeteam.website.modules.*.entity
  #加载映射文件
  mapper-locations: classpath:/mapper/*.xml
  #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      logic-delete-value: -1
      logic-not-delete-value: 0

#打印Sql语句
logging:
  level:
    #指定包路径,日志输出
    com.codeteam.website.modules.*.dao: debug